routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function(){
	return redirect('/ads');
});

Auth::routes();

// TODO: Rindirizza dopo aver visualizzato la pagina 'home'
Route::get('/home', 'HomeController@index')->name('home');

// Ads
/*
	Se non è presente la route GET '/ads' qualora la si cerci di raggiungere di si verifica il seguente errore: 'MethodNotAllowedHttpException'
	Source: https://github.com/laravel/framework/issues/24745
	// Route::get('/', 'AdsController@index')->name('ads.index');
*/
/*
Route::get('ads', function(){
	// return redirect('/');
	abort(404);
})->name('ads.index');
*/
Route::get('my-ads', 'AdsController@myAds')->name('my-ads');
Route::get('ads/{ad}/archive', 'AdsController@archive')->name('ads.archive');
Route::get('ads/archived', 'AdsController@archived')->name('ads.archived');

Route::resource('ads', 'AdsController', [
	// Esclude le seguenti azioni
	// 'except' => ['index']
]);

resources/views/partials/alerts.blade.php
@if (count($errors) > 0)
	<div class="alert alert-danger">
		<button type="button" class="close" data-dismiss="alert">×</button>
		<ul>
	    	@foreach ($errors->all() as $error)
				<li>{{ $error }}</li>
	    	@endforeach
		</ul>
	</div>
@endif


@if ($message = Session::get('error'))
	<div class="alert alert-danger alert-block">
	    <button type="button" class="close" data-dismiss="alert">×</button> 
	    <strong>{{ $message }}</strong>
	</div>

	@php
		Session::forget('error');
	@endphp
@endif


@if ($message = Session::get('warning'))
	<div class="alert alert-warning alert-block">
	    <button type="button" class="close" data-dismiss="alert">×</button> 
	    <strong>{{ $message }}</strong>
	</div>

	@php
		Session::forget('warning');
	@endphp
@endif


@if ($message = Session::get('info'))
	<div class="alert alert-info alert-block">
	    <button type="button" class="close" data-dismiss="alert">×</button> 
	    <strong>{{ $message }}</strong>
	</div>

	@php
		Session::forget('info');
	@endphp
@endif


@if ($message = Session::get('success'))
	<div class="alert alert-success alert-block">
		<button type="button" class="close" data-dismiss="alert">×</button> 
		<strong>{{ $message }}</strong>
	</div>

	@php
		Session::forget('success');
	@endphp
@endif

resources/views/partials/footer.blade.php
<footer class="footer text-light bg-dark text-center">
    <div class="container">
        <span>
            Created by
            <a href="mailto:victorputinelu95@gmial.com">VictorBP</a>
        </span>
    </div>
</footer>

resources/views/partials/navbar.blade.php
<nav class="navbar navbar-expand-md navbar-dark bg-dark navbar-laravel">
    <div class="container">
        <a class="navbar-brand" href="{{ url('/') }}">
            {{ config('app.name', 'Laravel') }}
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <!-- Left Side Of Navbar -->
            {{--
            <ul class="navbar-nav mr-auto">
            </ul>
            --}}

            <!-- Right Side Of Navbar -->
            <ul class="navbar-nav ml-auto">
                <!-- Authentication Links -->
                @guest
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                    </li>
                @else
                    <li class="nav-item" title="Post a new Ad">
                        <a href="{{ route('ads.create') }}" class="nav-link text-light">
                            <span class="display-4 nav-link-vertical-align">+</span>
                            <span class="nav-link-vertical-align">New Ad</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{{ route('my-ads') }}" class="nav-link nav-link-vertical-align">My Ads</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a id="navbarDropdown" class="nav-link dropdown-toggle nav-link-vertical-align" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                            {{ Auth::user()->name }} <span class="caret"></span>
                        </a>

                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">

                            <a class="dropdown-item" href="{{ route('ads.archived') }}">Archived Ads</a>

                            <a class="dropdown-item" href="{{ route('logout') }}"
                               onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                {{ __('Logout') }}
                            </a>

                            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                @csrf
                            </form>
                        </div>
                    </li>
                @endguest
            </ul>
        </div>
    </div>
</nav>